### PR TITLE
Do not hardcode region viriginia as a provider

### LINKED ISSUE #26: Review apps are always created in us-east-1 region
Hi,

I have a configuration that has
```
region = "eu-central-1"
```

However, all resources are created in `us-east-1`.

Thanks for your work, it saves a lot of time :)

### PR DESCRIPTION
**Pull request by dolohow**
Closes #26

### CODE REVIEW

**Comment by nagelflorian** [comment]
FYI I've responded on the issue. The e2e tests are failing for me too:

```
error creating CloudFront Distribution: InvalidLambdaFunctionAssociation: The function must be in region 'us-east-1'
```

**Comment by dolohow** [comment]
Yes, I saw that too when trying to migrate to different region. I'm thinking maybe just bucket could be in different region or not?

**Comment by nagelflorian** [comment]
Yes exactly, you can deploy the bucket in a different region than `us-east-1` by setting the region property of the module (see [`README.md`](https://github.com/nagelflorian/terraform-aws-s3-review-apps/blob/master/README.md)).

| Name | Description | Type | Default | Required |
| ----- | ------------ | ----- | -------- | :------: |
region | If specified, the AWS region this bucket should reside in. Otherwise, the region used by the callee | string | "us-east-1"

**Comment by dolohow** [comment]
but bucket region is hardcoded here:
https://github.com/nagelflorian/terraform-aws-s3-review-apps/blob/master/main.tf#L63

and `var.region` is actually never used

**Pull request closed without merging**
